#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "ChatRoomSys: self-hosted CD runner on IIS"

say "Run this ON the IIS server that hosts chat.alexdemo1.com — not on your dev"
say "machine. Every command below is meant to be pasted into an elevated"
say "PowerShell window on that server; this script just narrates the steps and"
say "waits for you between them."

# ── Stage 1: Windows features ──────────────────────────────────────────────
stage "Windows features IIS needs"
say "The CD workflow drives IIS with PowerShell's WebAdministration module and"
say "the site itself needs WebSocket support (the native WebSocket chat demo"
say "won't connect without it — SignalR would silently degrade instead)."
step "Open 'Turn Windows features on/off' (or Server Manager → Add Roles and"
step "Features on Windows Server), then under Internet Information Services:"
step "  Web Server (IIS) → Application Development → WebSocket Protocol  [check]"
step "  Web Server (IIS) → Management Tools → IIS Management Scripts and Tools  [check]"
note "On Windows Server you can do both from an elevated PowerShell instead:"
note "  Install-WindowsFeature -Name Web-WebSockets, Web-Scripting-Tools"
note "On Windows 10/11 (non-Server), the DISM equivalents are:"
note "  Enable-WindowsOptionalFeature -Online -FeatureName IIS-WebSockets"
note "  Enable-WindowsOptionalFeature -Online -FeatureName IIS-ManagementScriptingTools"
confirm "Both features enabled?" || warn "come back to this before you test the workflow"

# ── Stage 2: register a new runner on GitHub ───────────────────────────────
stage "Generate a runner registration token"
say "GitHub issues a short-lived token that authorizes one runner to register"
say "against this repo. You'll paste it into config.cmd on the server next."
open_url "https://github.com/Alex20211129/ChatHub/settings/actions/runners/new"
step "Choose Runner image: Windows, Architecture: x64."
step "Leave this page open — the 'Download' and 'Configure' boxes below it"
step "have the exact commands (including your token) you'll run on the server."
pause "Got the page open with the commands visible?"

# ── Stage 3: download + configure the runner ───────────────────────────────
stage "Download and configure the runner on the server"
say "These are the commands GitHub just showed you (yours will have a real"
say "token in the config.cmd line — don't reuse the placeholder below)."
note '  mkdir actions-runner ; cd actions-runner'
note '  Invoke-WebRequest -Uri https://github.com/actions/runner/releases/download/vX.Y.Z/actions-runner-win-x64-X.Y.Z.zip -OutFile actions-runner.zip'
note '  Expand-Archive -Path actions-runner.zip -DestinationPath $PWD'
note '  ./config.cmd --url https://github.com/Alex20211129/ChatHub --token <TOKEN_FROM_GITHUB_PAGE>'
step "When config.cmd asks for runner name/labels, defaults are fine — the"
step "cd.yml workflow only requires the runner to carry the 'self-hosted' and"
step "'Windows' labels, which are added automatically."
pause "config.cmd finished without errors?"

# ── Stage 4: install as a service with the right permissions ──────────────
stage "Install as a Windows service (with IIS control rights)"
warn "This is the one real trade-off in this setup, so read before running it."
say "The workflow calls Stop/Start-WebAppPool, Stop/Start-Website, and writes"
say "into C:\\inetpub\\wwwroot\\chatroomsys. Those all need more than a default"
say "low-privilege account has — IIS app-pool/site control isn't something you"
say "can delegate finely without setting up IIS's own feature-delegation rules,"
say "which is real effort for a one-site personal box. The pragmatic choice"
say "here is to run the runner service under an account that's a local"
say "Administrator. That's broad — the runner can do anything on this machine"
say "when a workflow runs — acceptable because: this box is single-purpose"
say "(hosts only this site), the repo is yours, and nobody else can push to"
say "'main' to make the runner execute arbitrary code. If any of that stops"
say "being true later, revisit this with per-resource ACLs instead."
step "Easiest path: create (or pick) a dedicated local account for the runner,"
step "add it to the local Administrators group, then install the service to"
step "run as that account:"
note '  ./svc.sh install <DOMAIN_OR_COMPUTERNAME>\<RunnerAccount>'
note '  (svc.sh will prompt for that account'"'"'s password)'
note '  ./svc.sh start'
step "If you'd rather keep it simple and this machine has no other purpose,"
step "installing the service under the default (LocalSystem-ish) account also"
step "works — LocalSystem already has full local machine rights, including IIS."
confirm "Service installed and running as an account with IIS admin rights?"

# ── Stage 5: confirm GitHub sees it ────────────────────────────────────────
stage "Verify the runner is online"
open_url "https://github.com/Alex20211129/ChatHub/settings/actions/runners"
step "Confirm your new runner shows status 'Idle' (green), not 'Offline'."
confirm "Runner shows Idle?"

# ── Stage 6: dry-run the CD workflow ───────────────────────────────────────
stage "Dry-run the deploy"
say "cd.yml has a workflow_dispatch trigger for exactly this — a manual run"
say "you can watch, without needing a new push."
open_url "https://github.com/Alex20211129/ChatHub/actions/workflows/cd.yml"
step "Click 'Run workflow' → Run on 'main'."
step "Watch the run: publish should succeed, then the 'Deploy to IIS' step"
step "stops the app pool/site, robocopies, and restarts them."
pause "Run finished green?"
say "Now check the server itself:"
step "Confirm C:\\inetpub\\wwwroot\\chatroomsys\\appsettings.Production.json"
step "still exists and is unchanged (robocopy was told to exclude it)."
step "Confirm C:\\inetpub\\wwwroot\\chatroomsys\\Logs\\ still has your old log"
step "files (robocopy was told to exclude that folder too)."
confirm "Both appsettings.Production.json and Logs/ survived the deploy?"

# ── Stage 7: confirm the live site ─────────────────────────────────────────
stage "Confirm the live site"
open_url "https://chat.alexdemo1.com"
step "Log in with a demo account and send a message in both /Chat/WebSocket"
step "and /Chat/SignalR to confirm both connection layers still work after"
step "the app pool restart."
confirm "Site loads and both chat demos work?"

finish
say "From now on, every push to main that passes CI will auto-deploy here."
say "EF Core migrations are NOT part of this pipeline on purpose — run"
say "'dotnet ef database update' by hand on the server when a change needs it."
